### ISSUE TITLE
Dumping assembler as string data documentation broken

### ISSUE THREAD

**Issue by GregoryMorse** [asmjit/asmjit#368]
Currently the example code given breaks as the `dump` function was removed

```
error C2039: 'dump': is not a member of 'asmjit::BaseBuilder'
```

First example on: https://asmjit.com/doc/classasmjit_1_1x86_1_1Builder.html
Also found in: https://github.com/asmjit/asmjit/blob/master/src/asmjit/x86/x86builder.h

I am investigating how to get this feature working again, but at a minimum the documentation should be updated and such comment removed from the source.

Offending commit is here: https://github.com/asmjit/asmjit/commit/996deae3273073bf75fbd6ddeac038dff5fdb6eb
